# Copy to .streamlit/secrets.toml or Streamlit Cloud secrets UI
ELEVENLABS_API_KEY = "replace_me"
STRIPE_API_KEY = "replace_me"
STRIPE_PRICE_ID = "price_xxx"  # optional if using pre-created Price
SENTRY_DSN = "https://examplePublicKey.ingest.sentry.io/project"
# Set to any value to force offline simulation (no external calls)
# VOCALBRAND_OFFLINE is environment variable, not secret; set in deployment settings if needed
